// default config
module.exports = {
    port: 8350,
    workers: 1,
    caseManager: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype",
        "therapistperiod",
        "complaint",
        "division",
        "therapist"
    ],
    divisionManager: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype",
        "therapistperiod",
        "complaint",
        "division",
        "station",
        "therapist"
    ],
    admin: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype",
        "therapistperiod",
        "complaint",
        "division",
        "divisionAdminRelation",
    ],
    therapist: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype",
        "therapistperiod",
        "complaint",
        "division",
        "therapist",
    ],
    client: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype",
        "therapistperiod",
        "complaint",
        "division",
        "therapist",
    ]
};
