// default config
module.exports = {
    port: 8350,
    workers: 1,
    caseManager: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype"
    ],
    divisionManager: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype"
    ],
    admin: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype"
    ],
    therapist: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype"
    ],
    client: [
        "login",
        "leveltype",
        "mannertype",
        "order",
        "push",
        "qualificationtype",
        "room",
        "roomoccupy",
        "schooltype",
        "user",
        "wechatApi",
        "consulttype"
    ]
};
